DoeLuz/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DoeLuz.Models;
using DoeLuz.Models.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace DoeLuz.Controllers
{
    public class AdminController : Controller
    {
        private ApplicationDbContext context;
        private IAdminRepositorio repositorio;
        public int PageSize = 4;
        public AdminController(IAdminRepositorio repo, ApplicationDbContext ctx)
        {
            repositorio = repo;
            context = ctx;
        }

        //view com a lista de admins
        public ViewResult List(int paginaAdmin = 1)
            => View(new AdminListViewModel
            {
                Admins = repositorio.Admins
                .OrderBy(a => a.AdminID)
                .Skip((paginaAdmin - 1) * PageSize)
                .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    PaginaAtual = paginaAdmin,
                    ItensPorPagina = PageSize,
                    TotalItens = repositorio.Admins.Count()
                }
            });

        //view para adicionar um administrador
        [HttpGet]
        public IActionResult New()
        {
            return View();
        }
        [HttpPost]
        public IActionResult New(Admin admin)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    repositorio.Create(admin);
                    return RedirectToAction("ConfirmaCadastro");
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        //view de confirmação
        public IActionResult ConfirmaCadastro()
        {
            return View();
        }
        public IActionResult Details(int id)
        {
            var admin = repositorio.ObterAdmin(id);
            return View(admin);
        }

        //view para editar um administrador
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var admin = context.Admins.Find(id);
            return View(admin);
        }
        [HttpPost]
        public IActionResult Edit(Admin admin)
        {
            repositorio.Edit(admin);
            return RedirectToAction("List");
        }

        //view para excluir um administrador
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var admin = repositorio.ObterAdmin(id);
            return View(admin);
        }
        [HttpPost]
        public IActionResult Delete(Admin admin)
        {
            repositorio.Delete(admin);
            return RedirectToAction("List");
        }
    }
}

DoeLuz/Controllers/BeneficiarioController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DoeLuz.Models;
using DoeLuz.Models.ViewModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DoeLuz.Controllers
{
    public class BeneficiarioController : Controller
    {
        private ApplicationDbContext context;
        private IBeneficiarioRepositorio repositorio;

        public int PageSize = 4;
        public  BeneficiarioController(IBeneficiarioRepositorio repo, ApplicationDbContext ctx)
        {
            repositorio = repo;
            context = ctx;
        }

        //Lista paginada de beneficiarios
        public ViewResult List(int paginaBeneficiario = 1) => View(new BeneficiarioListViewModel
        {
            Beneficiarios = repositorio.Beneficiarios
            .OrderBy(b => b.BeneficiarioID)
            .Skip((paginaBeneficiario - 1) * PageSize)
            .Take(PageSize),
            PagingInfo = new PagingInfo
            {
                PaginaAtual = paginaBeneficiario,
                ItensPorPagina = PageSize,
                TotalItens = repositorio.Beneficiarios.Count()
            }
        });

        //lista de beneficiados do mês, que o status é igual a disponivel
        public ViewResult ListStatus(int paginaBeneficiario = 1) => View(new BeneficiarioListViewModel
        {
            Beneficiarios = repositorio.Beneficiarios
            .Where(b => b.Status == "disponivel")
            .OrderBy(b => b.Nome)
            .Skip((paginaBeneficiario - 1) * PageSize)
            .Take(PageSize),
            PagingInfo = new PagingInfo
            {
                PaginaAtual = paginaBeneficiario,
                ItensPorPagina = PageSize,
                TotalItens = repositorio.Beneficiarios.Count()
            }
        });

        //lista com status igual a null ou indisponivel para o admin gerenciar
        public ViewResult ListforAdmin(int paginaBeneficiario = 1) => View(new BeneficiarioListViewModel
        {
            Beneficiarios = repositorio.Beneficiarios
            .Where(b => b.Status == null)
            .OrderBy(b => b.Nome)
            .Skip((paginaBeneficiario - 1) * PageSize)
            .Take(PageSize),
            PagingInfo = new PagingInfo
            {
                PaginaAtual = paginaBeneficiario,
                ItensPorPagina = PageSize,
                TotalItens = repositorio.Beneficiarios.Count()
            }
        });

        //list para o doador ver os benefiiciarios com status igual a disponivel
        public ViewResult ListparaDoador(int paginaBeneficiario = 1) => View(new BeneficiarioListViewModel
        {
            Beneficiarios = repositorio.Beneficiarios
            .Where(b => b.Status == null)
            .OrderBy(b => b.Nome)
            .Skip((paginaBeneficiario - 1) * PageSize)
            .Take(PageSize),
            PagingInfo = new PagingInfo
            {
                PaginaAtual = paginaBeneficiario,
                ItensPorPagina = PageSize,
                TotalItens = repositorio.Beneficiarios.Count()
            }            
        });

        //Criar novo beneficiario
        [HttpGet]
        public IActionResult New()
        {
            return View();
        }
        [HttpPost]
        public IActionResult New(Beneficiario beneficiario)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    repositorio.Create(beneficiario);
                    return RedirectToAction("ConfirmaCadastro");
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        //mostra os detalhes do cadastro
        public IActionResult Details(int id)
        {
            var beneficiario = repositorio.ObterBeneficiario(id);
            return View(beneficiario);
        }
        public IActionResult DetailsAdmin(int id)
        {
            var beneficiario = repositorio.ObterBeneficiario(id);
            return View(beneficiario);
        }

        //permite editar as informacoes do cadastro
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var beneficiario = context.Beneficiarios.Find(id);
            return View(beneficiario);
        }
        [HttpPost]
        public IActionResult Edit(Beneficiario beneficiario)
        {
            repositorio.Edit(beneficiario);
            return RedirectToAction("List");
        }

        [HttpGet]
        public IActionResult EditAdmin(int id)
        {
            var beneficiario = context.Beneficiarios.Find(id);
            return View(beneficiario);
        }
        [HttpPost]
        public IActionResult EditAdmin(Beneficiario beneficiario)
        {
            repositorio.Edit(beneficiario);
            return RedirectToAction("ListforAdmin");
        }

        public IActionResult ConfirmaCadastro()
        {
            return View();
        }

        //delte o cadastro
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var beneficiario = repositorio.ObterBeneficiario(id);
            return View(beneficiario);
        }
        [HttpPost]
        public IActionResult Delete(Beneficiario beneficiario)
        {
            repositorio.Delete(beneficiario);
            return RedirectToAction("List");
        }
    }
}

DoeLuz/Controllers/DoacaoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DoeLuz.Models;
using DoeLuz.Models.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace DoeLuz.Controllers
{
    public class DoacaoController : Controller
    {
        private IDoacaoRepositorio repositorio;
        private ApplicationDbContext context;
        public int PageSize = 4;
        public DoacaoController(IDoacaoRepositorio repo, ApplicationDbContext ctx)
        {
            repositorio = repo;
            context = ctx;
        }

        //retorna lista de doacoes paginada
        public ViewResult List(int paginaDoacao = 1) => View(new DoacaoListViewModel
        {
            Doacoes = repositorio.Doacoes
                .OrderBy(d => d.DoacaoID)
                .Skip((paginaDoacao - 1) * PageSize)
                .Take(PageSize),
            PagingInfo = new PagingInfo
            {
                PaginaAtual = paginaDoacao,
                ItensPorPagina = PageSize,
                TotalItens = repositorio.Doacoes.Count()
            }
        });

        //view para cadastrar nova doacao
        [HttpGet]
        public IActionResult New()
        {
            ViewBag.DoadorID = new SelectList(context.Doadores.OrderBy(d => d.Nome),"DoadorID", "Nome");
            ViewBag.BeneficiarioID = new SelectList(context.Beneficiarios.Where(d => d.Status=="disponivel").OrderBy(b => b.Nome),"BeneficiarioID","Nome");
            ViewBag.AdminID = new SelectList(context.Admins.OrderBy(a => a.NomeOng),"AdminID", "NomeOng");
            return View();
        }
        [HttpPost]
        public IActionResult New(Doacao doacao)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    repositorio.Create(doacao);
                    return RedirectToAction("ConfirmaCadastroAdmin");
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

    //Aqui o doador vai realizar a doação direta para o beneficiario
        [HttpGet]
        public IActionResult DoacaoDireta()
        {
            ViewBag.DoadorID = new SelectList(context.Doadores.OrderBy(d => d.Nome),"DoadorID", "Nome");
            ViewBag.BeneficiarioID = new SelectList(context.Beneficiarios.Where(d => d.Status == "disponivel").OrderBy(b => b.Nome),"BeneficiarioID", "Nome");
            ViewBag.AdminID = new SelectList(context.Admins.OrderBy(a => a.Nome),"AdminID", "NomeOng");
            return View();
        }

        [HttpPost]
        public IActionResult DoacaoDireta(Doacao doacao)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    repositorio.Create(doacao);
                    return RedirectToAction("ConfirmaCadastro");
                }
                return View();
            }
            catch
            {
                return View();
            }
        }
        //Aqui o admin vai cadastrar uma doação
        [HttpGet]
        public IActionResult DoarAdmin()
        {
            ViewBag.DoadorID = new SelectList(context.Doadores.OrderBy(d => d.Nome),"DoadorID", "Nome");
            ViewBag.BeneficiarioID = new SelectList(context.Beneficiarios.OrderBy(b => b.Nome),"BeneficiarioID", "Nome");
            ViewBag.AdminID = new SelectList(context.Admins.OrderBy(a => a.NomeOng),"AdminID", "NomeOng");
            return View();
        }

        [HttpPost]
        public IActionResult DoarAdmin(Doacao doacao)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    repositorio.Create(doacao);
                    return RedirectToAction("ConfirmaCadastro");
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        //view para exibir os detalhes da doacao
        public IActionResult Details(int id)
        {
            var doacao = repositorio.ObterDoacao(id);
            return View(doacao);
        }

        public IActionResult ConfirmaCadastro()
        {
            return View();
        }

        public IActionResult ConfirmaCadastroAdmin()
        {
            return View();
        }

        //view para editar as informações da doação
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var doacao = context.Doacoes.Find(id);
            ViewBag.DoadorID = new SelectList(context.Doadores
                .OrderBy(d => d.Nome), "Nome");
            ViewBag.BeneficiarioID = new SelectList(context.Beneficiarios
                .OrderBy(b => b.Nome), "Nome");
            ViewBag.AdminID = new SelectList(context.Admins
                .OrderBy(a => a.Nome), "Nome");
            return View(doacao);
        }
        [HttpPost]
        public IActionResult Edit(Doacao doacao)
        {
            repositorio.Edit(doacao);
            return RedirectToAction("List");
        }

        //view para excluir uma doação
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var doacao = repositorio.ObterDoacao(id);
            return View(doacao);
        }
        [HttpPost]
        public IActionResult Delete(Doacao doacao)
        {
            repositorio.Delete(doacao);
            return RedirectToAction("List");
        }

    }
}

DoeLuz/Controllers/DoadorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DoeLuz.Models;
using DoeLuz.Models.ViewModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DoeLuz.Controllers
{
    public class DoadorController : Controller
    {
        private IDoadorRepositorio repositorio;
        private ApplicationDbContext context;
        public int PageSize = 4;
        public DoadorController(IDoadorRepositorio repo, ApplicationDbContext ctx)
        {
            context = ctx;
            repositorio = repo;
        }
        //gera a lista paginada de doadores
        public ViewResult List(int paginaDoador = 1) => View(new DoadorListViewModel
        {
            Doadores = repositorio.Doadores
            .OrderBy(d => d.DoadorID)
            .Skip((paginaDoador - 1) * PageSize)
            .Take(PageSize),
            PagingInfo =  new PagingInfo
            {
                PaginaAtual = paginaDoador,
                ItensPorPagina = PageSize,
                TotalItens = repositorio.Doadores.Count()
            }
        });

        //view para cadastrar novo doador
        [HttpGet]
        public IActionResult New()
        {
            return View();
        }
        [HttpPost]
        public IActionResult New(Doador doador)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    repositorio.Create(doador);
                    return RedirectToAction("ConfirmaCadastro");
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        public IActionResult ConfirmaCadastro()
        {
            return View();
        }
        //View para exibir as informações dos doadores
        public IActionResult Details(int id)
        {
            var doador = repositorio.ObterDoador(id);
            return View(doador);
        }
        public IActionResult DetailsAdmin(int id)
        {
            var doador = repositorio.ObterDoador(id);
            return View(doador);
        }

        //View para editar as informações do doador
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var doador = context.Doadores.Find(id);
            return View(doador);
        }
        [HttpPost]
        public IActionResult Edit(Doador doador)
        {
            repositorio.Edit(doador);
            return RedirectToAction("List");
        }
        [HttpGet]
        public IActionResult EditAdmin(int id)
        {
            var doador = context.Doadores.Find(id);
            return View(doador);
        }
        [HttpPost]
        public IActionResult EditAdmin(Doador doador)
        {
            repositorio.Edit(doador);
            return RedirectToAction("List");
        }

        //view para excluir um cadastro
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var doador = repositorio.ObterDoador(id);
            return View(doador);
        }
        [HttpPost]
        public IActionResult Delete(Doador doador)
        {
            repositorio.Delete(doador);
            return RedirectToAction("List");
        }
    }
}

DoeLuz/Views/SessionControler/Home.cshtml
@using Microsoft.AspNetCore.Http;
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
    Layout = null;
}
<!DOCTYPE html>

<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width , initial-scale=1, shrink-to-fit=no" />
    <link rel="stylesheet" asp-href-include="/lib/bootstrap/dist/**/*.min.css" />
    <title>Doe Luz</title>
</head>
<body style="padding-top:5em">
    <nav class="navbar navbar-expand-lg navbar-dark badge-danger fixed-top" style="background-color: #D46A6B;" role="navigation">
        <div class="container">
            <a class="navbar-brand h1 mb-0" href="#">DOE LUZ</a>
            <div>
                @Html.ActionLink("Sair", "Login", "SessionControler", null, new { @class = "navbar-brand" })
            </div>
        </div>
    </nav>
    <div class="row m-1 p-1">
        <div id="categories" class="col-2">
            <img src="/lib/bootstrap/js/src/logo.jpg" alt="" width="150" height="100">
        </div>

        <div class="mt-5 col-lg-9">
            <h1 style="text-align:center">Bem vindo @HttpContextAccessor.HttpContext.Session.GetString("usuario_session")!</h1>
            @Html.ActionLink("Cadastrar doação", "New", "Doacao", null, new { @class = "btn btn-danger btn-lg btn-block rounded-pill" })
            @Html.ActionLink("Lista de Beneficiários", "List", "Beneficiario", null, new { @class = "btn btn-danger btn-lg btn-block rounded-pill" })
            @Html.ActionLink("Lista de Doadores", "List", "Doador", null, new { @class = "btn btn-danger btn-lg btn-block rounded-pill" })
            @Html.ActionLink("Gerenciar Administradores", "List", "Admin", null, new { @class = "btn btn-danger btn-lg btn-block rounded-pill" })
            @Html.ActionLink("Gerar Beneficiarios do Mês", "ListStatus", "Beneficiario", null, new { @class = "btn btn-danger btn-lg btn-block rounded-pill" })
            @Html.ActionLink("Relatório de Doações", "List", "Doacao", null, new { @class = "btn btn-danger btn-lg btn-block rounded-pill" })
            @Html.ActionLink("Editar Status de Beneficiario", "ListforAdmin", "Beneficiario", new { id = @HttpContextAccessor.HttpContext.Session.GetInt32("id_session") }, new { @class = "btn btn-danger btn-lg btn-block rounded-pill" })
            @Html.ActionLink("Suas Informações", "Details", "Admin", new { id = @HttpContextAccessor.HttpContext.Session.GetInt32("id_session") }, new { @class = "btn btn-danger btn-lg btn-block rounded-pill" })

        </div>
    </div>
    <footer class="border-top footer text-muted" style="background-color: #D46A6B;">
        <div class="container ">
            <div class="row d-flex justify-content-xl-between">
                <div class="info float-left" style="color:white; padding-top:1em">
                    <h5>Entre em contato conosco!</h5>
                    <h6>Centro Espírita Caminho da Luz</h6>
                    <p class="ml-3">
                        Telefone: (35) 99915-4779<br />
                        Email: paulogustavovilela@gmail.com<br />
                        Endereço: Rua da Liberdade, 151 - Vila Betânia
                    </p>
                </div>
                <div class="info float-right" style="color:white; padding-top:1em">
                    <h5>Desenvolvido por:</h5>
                    <div>
                        <a class="ml-3">Lucas Cruz</a>
                        <a class="bi bi-github ml-2" href="https://github.com/CruzLucass" style="color: white;">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                                <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z" />
                            </svg>
                        </a>
                        <br />
                        <a class="ml-3">Leonardo Garroni</a>
                        <a class="bi bi-github ml-2" href="https://github.com/leogarroni" style="color: white;">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                                <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z" />
                            </svg>
                        </a>
                        <br />
                        <a class="ml-3">Athie Brito</a>
                        <a class="bi bi-github ml-2" href="https://github.com/athiebrito" style="color: white;">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                                <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z" />
                            </svg>
                        </a>
                    </div>
                </div>
                <div class="col-sm-3 info" style="color:white">
                </div>
            </div>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>